name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: '50 23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Fetch data 
        uses: githubocto/flat@mr/node20
        with:
          http_url: https://api.joinmastodon.org/statistics
          downloaded_filename: statistics-response.json
          postprocess: postprocess.js
