name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '50 23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: 'https://api.joinmastodon.org/statistics'
          downloaded_filename: 'data.json'
